name: "Multi event pipeline/workflow" #Name of pipline

on:
    push:    #Event : Whenever push is made on the master branch
        branches:
            - master
            - test
            - prod
        
    schedule:
    - cron: "0 10 * * 2,4"
    
    pull_request:
             branches:
               - master
             types:
             - closed
             - opened

            
jobs:
    on-push:     #job 1
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:   #Steps to be executed in the jobs
            - name: "Running on Master push"   #Step 1
              run: echo "Running on master push"

    on-pull-request: #job 2
              if: github.event_name == 'pull_request'
              runs-on: ubuntu-latest
              steps: #Steps to be executed in the jobs
                - name: "Running on pull request" #Steps 2
                  run: echo "Running on pull request"
    on-schedule: #job 3
             if: github.event_name == 'schedule'
             runs-on: ubuntu-latest
             steps: #Steps to be executed in the jobs
             - name: "Running on scheduled time" #Steps 3
               run: echo "Running on scheduled time"